---
output: html_fragment
---

<!-- place activity 1 here -->

In a sequential optimization, we begin with an initial set of factor levels and measure the response as we change one factor's level and hold constant the level of the other factor. When the response no longer improves, we hold the first factor constant and monitor the response as we change the second factor's level.This pattern continues until there is no further increase in the response. The controls allow you to choose a response surface, to set the initial values for the two factors, to observe the optimization's path in 2D and 3D, to overlay the path on a contour (2D) or surface (3D) plot, and to rotate and tilt the latter. Factor A is optimized first and the step-size is limited to $0$ or $\pm 1$.

**Exercise 1**. Begin with the first response surface, set (A,B) to ($0,0$), and choose to display the path only in 2D. Note the position of the optimum response. Set the display to path only in 3D and compare the 2D and 3D views to each other. What additional information is available from the 3D view? Change the initial factor levels to ($10,0$), ($0,10$), ($10,10$), and (5,5). Is the optimum response sensitive to the initial factor levels? Repeat for the other response surfaces.

**Exercise 2**. Look at the optimization paths from Exercise 1 and predict the shape of the four response surfaces in 2D and in 3D. When you are done, set the display to path & surface in 2D, which overlays the optimization on a 2D contour plot of the response surface. Is the display consistent with your prediction of the response surface's shape? Set the display to path & surface in 3D, which overlays the optimization on a 3D surface plot. Is the display consistent with your prediction of the response surface's shape? What do your results suggest about the effectiveness of a sequential optimization?

**Exercise 3**. Using the first example, set the initial factor levels to ($0,0$) and count the number of steps it takes to reach the optimum response, and the number of times the algorithm switches between the two factors. Repeat for the other three examples. What do your results suggest about the efficiency of a sequential optimization?
