---
output: html_fragment
---

<!-- place activity 4 here -->

The efficiency and effectiveness of a fixed-size simplex optimization is limited by the size of the initial simplex. A small simplex is less efficient because it requires more experiments to reach the optimum response, and a large simplex is less effective if its size prevents a vertex from aligning closely with the optimum response. In a variable-sized simplex optimization we allow the simplex to expand or contract in response to the relative change in the response. The figure on the second line of controls shows how the simplex moves. The solid circles show the current simplex. The response at each point is measured and ranked as best (B), next best (NB), and worst (W) responses. The worst vertex is replaced by reflecting it through the line connecting B and NB. Depending on the response for R relative to B, NB, and W, the new vertex can extend to E or contract to CR or to CW. Optimization continues until the simplex no longer moves.

**Exercise 1**. Select the first response surface and set the initial factor levels to $(1,1)$ with an orientation of 4. Using the slider for iterations to 1 and step through the iterations, identifying for each the vertex that is rejected and the new vertex that replaces it. Can you identify the conditions that lead to expanding, retaining, or contracting the reflected vertex? How many iterations does it take to reach the optimum response? How does this compare to a fixed-size simplex optimization?

**Exercise 2**. Explore the utility of the variable-sized simplex optimization for optimizing the response surfaces in all four examples. How effective is the variable-sized simplex optimization in locating the maximum responses? Does the initial position and orientation of the simplex affect the algorithm's effectiveness or efficiency? 

**Exercise 3**. Pick one of the four response surfaces and complete the optimization using each of the four algorithms. Use the same initial factor levels of $(2,2)$ in each case, and use a step-size of 1 for the fixed-size simplex optimization to be compatible with the initial step-size of the other algorithms. Repeat using initial factor levels of $(2,8)$, $(8,2)$, and $(8,8$). Compare the algorithms in terms of the effectiveness and their efficiency.
