---
output: html_fragment
---

<!-- place activity 2 here -->

Although a sequential optimization generally is effective, it often is not efficient because it adjusts only one factor at a time. A more efficient algorithm adjusts all factors at the same time, moving in the direction that provides the greatest change (steepest ascent) in the response. 

The controls on the right are identical to those on the previous tab with the exception that the optimization's path is always superimposed on the 2D contour plot or the 3D surface plot. The direction of the steepest ascent is evaluated by comparing the response in eight directions: to the north, to the east, to the south, to the west, to the northeast, to the southeast, to the southwest, and to the northwest The four response surfaces are identical to those on the previous tab. 

**Exercise 1**. Select the first response surface, set the initial factor levels to $(0,0)$,  and choose the display that shows a contour plot in 2D. Explain how you can tell that the path to the maximum response at (3,7) is a steepest ascent optimization and not a sequential optimization.

**Exercise 2**. Select the second example, set the initial factor levels to $(10,0)$, and choose the display to show a contour plot in 2D. How many steps does it take to reach the optimum response? Set up the same optimization using a sequential optimization, and determine how many steps it takes to reach the optimum response. Explain why the two algorithms take such different pathways and have such different efficiencies even though they begin in the same place and end in the same place. 

**Exercise 3**. Explore the relative efficiencies of a sequential and a steepest ascent algorithm for all four response surfaces. Are there shapes of response surfaces and/or locations of initial starting points where their efficiencies are similar? Are there shapes of response surfaces and/or location of initial starting points where their efficiencies are different? 
