---
output: html_fragment
---

<!-- place activity 3 here -->

The algorithms for a sequential and a steepest ascent optimization of two factors compares the responses for two points. A more efficient algorithm will use more than two points. One example compares the response for three pairs of factor levels, which form the vertices of a triangle. This pattern is called a simplex. The first simplex is defined---using the figure on the upper-left of the controls---by providing the factor levels for the central point in blue, and by selecting an integer from 1 to 6 that gives the location of the remaining two points; the length of a simplex's sides is given by the slider on the lower right.

The figure on the second line of controls shows how the simplex moves. The solid circles show the current simplex. The response at each point is measured and ranked as the best (B), next best (NB), and worst (W) responses. The worst vertex is replaced by reflecting it through the line connecting B and NB; the new simplex is defined by B, NB, and R. Optimization continues until the simplex no longer moves.

**Exercise 1**. A simplex is the simplest object we can draw in *N*-dimensional space where *N* is the number of factors. The simplest figure we can draw in two-dimensions is a triangle. What makes a triangular-shaped simplex more efficient than a sequential or a steepest ascent optimization? 

**Exercise 2**. Select the first response surface, set the initial factor levels to $(2,2)$ with an orientation of 4 and a step-size of 1. Beginning with the initial simplex (outlined by the filled circles), identify the vertex that is rejected and the new vertex that replaces it. Repeat for the remaining simplexes. How many steps make up the optimization's pathway?

**Exercise 3**. Explore the utility of a fixed-size simplex for optimizing each of the four response surfaces. How effective is the simplex optimization in locating their maximum responses? Does the initial orientation and position of the simplex affect the algorithm's effectiveness or its efficiency? Does the size of the initial simplex affect the algorithm's effectiveness or its efficiency?
