---
output: html_fragment
---

<!-- place wrapping up here -->

#### Response Surfaces Used in this Module

The figures to the right show the four response surfaces used in this module where the factor levels for *A* and *B* are restricted to integer values between 0 and 10.

***example 1 (upper left)***: The equation for this response surface is a second-order polynomial in *A* and in *B* without an interaction between the two factors. 

$$1.68 + 0.24 \times A + 0.56 \times B - 0.04 \times A^2 - 0.04 \times B^2$$ 

When the $A^2$ and the $B^2$ terms are both negative and similar in value, as they are here, the resulting response surface has a dome-like shape. The response surface's maximum response is at (3,7). 

***example 2 (upper right)***: The equation for this response surface is a first-order polynomial in *A* with an interaction between *A* and *B*.

$$4.0 - 0.4 \times A + 0.08 \times A \times B$$ 

Note that when factor level for *A* is zero, the response is held constant at 4 for all values of *B*; this is because *B* only appears in the equation's final interaction term. The response surface's maximum response is at (10,10). 

***example 3 (lower left)***: The equation for this response surface is a second-order polynomial in *A* and in *B* with an interaction between the two factors. 

$$3.264 + 1.537 \times A + 0.5664 \times B - 0.1505 \times A^2 - 0.02734 \times B^2 - 0.05785 \times A \times B$$ 

When the $A^2$ and the $B^2$ terms are both negative, as is the case here, but not close in value to each other, the resulting response surface has a ridge-like shape. Although the response surface's maximum response is at (3.91,6.22), the restriction that all values of *A* and *B* are integers means it appears at (4,6). 

***example 4 (lower right)***: The equation for this response surface is a second-order polynomial in *A* and in *B* without an interaction between the two factors.

$$4 + 0.8 \times A - 0.7 \times B - 0.09 \times A^2 + 0.08 \times B^2$$ 

When one of second-order terms ($A^2$ and $B^2$) is negative and one is positive, as is the case here, and when they are similar in magnitude, the resulting response surface has a saddle-like shape. Although the response surface's maximum response is at (4.38,0), the restriction that all values of *A* and *B* are integers means it appears at (4,0). Note that there also is a local optimum at (4,10). 

You can explore the relationship between the signs and relative magnitudes of *A* and *B* and the shape of a second-order polynomial equation using the module *AC 3.0: Introduction to Response Surfaces*.

#### Rotating Surface Plots

There are a variety of functions in `R` to display data in three dimensions, such as the `persp` function used in this module. Such functions use two angles---theta and phi---to define the direction in which you view the data. These angles are typically defined only as the azimuthal angle and the colatitude angle. Unless you know how to navigate by the stars, you likely are not familiar with the practical meaning of these terms; thus, we describe them here as the angle by which we rotate the *xy*-plane around the *z*-axis (the azimuthal angle) and the angle by which we tilt the *z*-axis relative to the original *xy*-plane (the colatitude angle).

#### Additional Resources

For an introduction to response surfaces and the mathematical modeling of response surfaces, see Chapter 14 in [Analytical Chemistry 2.1](https://chem.libretexts.org/Bookshelves/Analytical_Chemistry/Analytical_Chemistry_2.1_(Harvey)/14%3A_Developing_a_Standard_Method/14.01%3A_Optimizing_the_Experimental_Procedure) and Chapter 9 in [Chemometics Using R](https://chem.libretexts.org/Bookshelves/Analytical_Chemistry/Chemometrics_Using_R_(Harvey)/09%3A_Gathering_Data). Another useful text is S. N. Deming and S. L. Morgan, *Experimental Design: A Chemometric Approach*, Elsevier: Amsterdam, 1987.

The description of the spot test for vanadium, included in the module's introduction, is based on a procedure outlined in *Vogel’s Textbook of Quantitative Inorganic Analysis*, Longman: London, **1978**, p. 752, and the article ["Simplex Optimization of Chemical Systems," Shavers, C. L.; Parsons, M. L.; Deming, S. N. *J. Chem. Educ.* **1979**, *56*, 307--309](https://doi.org/10.1021/ed056p307).

Another browser-based application that explores the variable-sized simplex optimization is available [here](http://195.134.76.37/applets/AppletSimplex/Appl_Simplex2.html).





